# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# platform: syntax
community_bridge: # Replace with PROJECT-NAME
github: # [USERNAME1, USERNAME2, USERNAME3, USERNAME4] Replace with up to 4 GitHub Sponsors-enabled usernames
issuehunt: # Replace with USERNAME
ko_fi: # Replace with USERNAME
liberapay: # Replace with USERNAME
open_collective: # Replace with USERNAME
otechie: # Replace with USERNAME
patreon: # Replace with USERNAME
tidelift: # Replace with PLATFORM-NAME/PACKAGE-NAME
custom: # Replace with ['link1', 'link2'] # Replace with up to 4 custom sponsorship URLs e.g., ['http://example.com', 'http://example.org']
