#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"

if [ $? -eq 0 ]; then
    echo
    echo "Commit message validation successful. Your message adheres to the Conventional Commits specification."
    echo
else
    echo
    echo "Commit message validation failed. Please revise your commit message to comply with the Conventional Commits specification. For guidelines, see [link-to-conventional-commits]."
    echo
fi